version: '3.8'
services:
  api:
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    volumes:
      - db:/app/prisma/db

volumes:
  db:
