name: Build and Test

# run workflow on push to main branch and pull requests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: file:./test.db
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Cache node_modules
        id: node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install dependencies
        run: yarn install
      - name: Create PrismaClient after installing dependencies
        run: yarn prisma:generate
      - name: Check for formatting issues
        run: yarn lint:format
      - name: Build application
        run: yarn build
      - name: Run unit tests
        run: yarn test:unit
      - name: Run integration tests
        run: yarn integration
